- name: initialize the cluster
  become: yes
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all

- name: create .kube directory
  file:
    path: /home/pi/.kube
    state: directory
    mode: 0755
  become: no

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/pi/.kube/config"
    remote_src: yes
    owner: "pi"
  become: yes

- name: enable ability to schedule pods on the control-plane node (master)
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  when: false

- name: install pod network add-on
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml
  become: no

- name: get join command
  become: yes
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
